# -*- coding: utf-8 -*-
"""Exercises_XP_Day2_Student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xN4dGoxH_l5j8eCGyTeF-6JCeLNu5out

# Exercises XP: Day 2
Follow the instructions. Where you see TODO, add your answer before running/continuing.

## What You'll Learn
- Deepen your understanding of core LLM concepts.
- Apply theory to practical scenarios.
- Develop critical thinking on LLM applications and ethics.
- Compare/contrast transformer architectures and techniques.

## What You Will Create
- Comparative tables (NLP paradigms and BERT variants)
- Architecture/application write-ups
- Pretraining benefits and ethical considerations
- Analyses on attention and positional encoding
- Model selection justifications across tasks
- Notes on softmax temperature and its effects
- Scenario-based answers applying learned concepts

## 🌟 Exercise 1: Traditional vs. Modern NLP: Comparative Analysis
1) Complete the table (replace each TODO):

| Aspect | Traditional NLP | Modern NLP |
|---|---|---|
| Feature Engineering | Manual feature engineering using linguistic rules (e.g., POS tags, n-grams, syntactic patterns). | Automatic feature learning from data using neural networks. |
| Word Representations | Sparse representations such as Bag-of-Words, TF-IDF, or one-hot vectors. | Dense embeddings such as Word2Vec, GloVe, or contextual embeddings (e.g., BERT). |
| Model Architectures | Statistical models like Naive Bayes, Hidden Markov Models (HMM), and Conditional Random Fields (CRF). | Deep learning architectures such as RNNs, LSTMs, CNNs, and Transformers. |
| Training Methodology | Models trained on task-specific datasets with handcrafted features. | End-to-end learning with large datasets and pretraining followed by fine-tuning. |
| Key Examples | N-gram language models, rule-based systems, CRF for sequence labeling. | Transformer-based models such as BERT, GPT, and T5. |
| Advantages | Interpretable, requires less data, computationally lighter. | Higher accuracy, better context understanding, adaptable to many tasks. |
| Disadvantages | Limited scalability, requires heavy manual effort, weaker performance on complex language tasks. | Requires large datasets, high computational cost, and significant hardware resources. |

2) Discuss: How did the shift to modern NLP impact scalability and efficiency?

- TThe transition from traditional NLP to modern NLP significantly improved scalability and efficiency by relying on representation learning instead of manual feature engineering. Neural models learn meaningful word representations automatically, allowing them to capture semantic and contextual relationships in large datasets. Modern architectures such as transformers are designed to leverage hardware parallelism, especially GPUs and TPUs, enabling faster training on massive corpora. This parallel computation makes it feasible to train very large models efficiently compared to sequential methods used in earlier architectures like RNNs. Additionally, transfer learning has transformed NLP workflows by allowing pretrained models to be fine-tuned for many downstream tasks, reducing the need to train models from scratch. As a result, organizations can reuse large pretrained models and adapt them quickly to new tasks. Overall, these advances have made NLP systems more scalable, accurate, and easier to deploy across diverse applications.

## 🌟 Exercise 2: LLM Architecture and Application Scenarios
For each, describe (a) core architectural differences, (b) a real application, (c) why it fits.

### BERT
- Core Architecture: Bidirectional encoder-only transformer. It reads the entire sentence at once and learns context from both the left and right sides of each word. It is trained mainly using Masked Language Modeling (MLM) and historically Next Sentence Prediction (NSP).

- Application: Named Entity Recognition (NER) or text classification (e.g., sentiment analysis).

- Why: Because BERT captures deep bidirectional context, it understands the meaning of words depending on the surrounding words in the sentence. This makes it very effective for understanding tasks where the goal is to classify or label text rather than generate new text.

### GPT
- Core Architecture: Decoder-only transformer trained with an autoregressive causal language model. It predicts the next token based only on the previous tokens in the sequence.

- Application: Chatbots, text generation, and code generation.

- Why: GPT is optimized for generating coherent sequences of text, since it learns to predict the next word step-by-step. This makes it well suited for conversational AI, creative writing, and programming assistance.

### T5
- Core Architecture: Encoder–decoder transformer using a text-to-text framework, where every task is converted into a text input and text output format.

- Application: Text summarization or machine translation.

- Why: The encoder processes the input text while the decoder generates the output sequence. This structure is ideal for sequence-to-sequence tasks, such as transforming a long document into a summary or translating text from one language to another.

## 🌟 Exercise 3: Benefits and Ethics of Pre-training

### Benefits

**Improved generalization:**  
Pre-trained models learn patterns from very large and diverse datasets. Because of this broad exposure to language, they can perform well on new tasks or unseen data even if the exact examples were not present during training.

**Less labeled data:**  
Since the model already learns general language knowledge during pre-training, only a small amount of labeled data is needed for a specific task. This reduces the time and cost required for data annotation.

**Faster fine-tuning:**  
Instead of training a model from scratch, we start from a pretrained model that already understands language structures. Fine-tuning only adjusts the model slightly for a specific task, making training much faster and computationally cheaper.

**Transfer learning:**  
Knowledge learned during pre-training can be reused for many different tasks. For example, a model trained on large text corpora can later be adapted for sentiment analysis, translation, or question answering.

**Robustness:**  
Because the model has seen many variations of language during pre-training, it becomes more resilient to noise, different writing styles, and varied contexts. This improves its ability to handle real-world inputs.

---

### Ethical Concerns

Large language models can reflect **bias** present in the training data, potentially producing unfair or discriminatory outputs. They may also generate **misinformation** or inaccurate content that appears convincing. Another concern is **misuse**, such as generating spam, fake news, or malicious code. Additionally, **privacy issues** can arise if the training data contains sensitive or personal information that the model might reproduce.

---

### Mitigations

**Data curation:** Carefully filtering and balancing training datasets to reduce harmful or biased content.

**Differential privacy:** Applying techniques that prevent the model from memorizing and revealing sensitive information from the training data.

**Safety filters:** Implementing systems that detect and block harmful or unsafe outputs.

**RLHF (Reinforcement Learning from Human Feedback):** Using human feedback to guide the model toward safer, more helpful responses.

**Audits:** Regularly evaluating models to detect biases, safety risks, and performance issues, and improving them based on the findings.

## 🌟 Exercise 4: Transformer Architecture Deep Dive

### Self-Attention & Multi-Head Attention

**Q/K/V Flow, Softmax Weighting, and Value Mixing**

In the self-attention mechanism, each word in a sentence is transformed into three vectors: **Query (Q)**, **Key (K)**, and **Value (V)**.  
The **Query** of a word is compared with the **Keys** of all other words in the sentence to compute similarity scores.  
These scores are then passed through a **softmax function**, which converts them into normalized attention weights.  
The weights indicate how much attention a word should give to other words in the sequence.  
Finally, the weights are multiplied by the **Value vectors**, and the results are combined to produce a contextual representation of the word.

**Why Multiple Heads Help**

Multi-head attention allows the model to perform attention in several different **representation subspaces** at the same time.  
Each head learns different relationships between words.  
This enables the model to capture **various linguistic patterns**, such as syntactic relations, semantic similarities, or long-range dependencies.  
As a result, the model gains a richer understanding of the sentence.

**Example Sentence**

*Sentence:*  
"The scientist explained the experiment to the students because they were curious."

Possible relations captured by different heads:

- **Head 1:** May focus on the relation between *scientist* and *explained* (subject–verb relationship).
- **Head 2:** May capture the reference between *they* and *students* (coreference resolution).

---

### Pre-training Objectives

**MLM vs CLM**

- **Masked Language Modeling (MLM):** Some words in a sentence are masked, and the model must predict the missing words using both left and right context. This approach is used in models like BERT.
- **Causal Language Modeling (CLM):** The model predicts the next word in a sequence based only on the previous words. This is the objective used in models like GPT.

**When to Prefer MLM vs CLM**

MLM is preferred for **language understanding tasks**, such as classification, NER, or question answering, because it uses full bidirectional context.  
CLM is preferred for **text generation tasks**, such as chatbots, storytelling, or code generation, because it naturally models sequential text generation.

**NSP (Next Sentence Prediction)**

Next Sentence Prediction was used in early BERT models to help the model understand relationships between sentences.  
The model learns to predict whether one sentence logically follows another.  
However, many modern models avoid NSP because later research showed that it does not significantly improve performance compared to other training strategies.

---

### Transformer Model Selection

**Sentiment on Reviews**

Recommended model: **Encoder-only (e.g., BERT)**  
Justification: Sentiment analysis is a **text understanding and classification task**, where the goal is to analyze the meaning of the input text rather than generate new text.

**Conversational Chatbot (Creative Responses)**

Recommended model: **Decoder-only (e.g., GPT)**  
Justification: Decoder-only models are optimized for **autoregressive text generation**, which makes them well suited for producing coherent and creative conversational responses.

**Technical Document Translation (EN → ES)**

Recommended model: **Encoder–Decoder (e.g., T5)**  
Justification: Translation is a **sequence-to-sequence task**, where the model must transform an input sentence in one language into another language. Encoder–decoder architectures handle this mapping effectively.

---

### Positional Encoding

**Purpose**

Transformers process all tokens in parallel, which means they do not naturally understand the order of words in a sentence.  
**Positional encoding** adds information about the position of each token so the model can understand the structure and sequence of the text.

**Example Failure Without Positions**

Without positional encoding, the model would treat the sentences:

- "The dog chased the cat."
- "The cat chased the dog."

as nearly identical because they contain the same words.  
However, the meaning is different due to the **word order**, which positional encoding helps the model capture.

## Exercise 5: BERT Variations: Choose Your Detective

### Scenario Assignments

**Scenario 1 (mobile, limited resources):**  
**DistilBERT** – It is a distilled version of BERT that is smaller and faster while keeping most of the performance. This makes it suitable for mobile devices and environments with limited computational resources.

**Scenario 2 (legal docs, high accuracy):**  
**RoBERTa** – It improves BERT training by using more data and removing certain limitations in the original training process, which leads to higher accuracy. This makes it appropriate for complex domains such as legal document analysis.

**Scenario 3 (multilingual support):**  
**XLM-R (XLM-RoBERTa)** – It is trained on large multilingual datasets and supports many languages, making it ideal for multilingual NLP tasks.

**Scenario 4 (efficient pretraining with token replacement detection):**  
**ELECTRA** – Instead of predicting masked tokens, it detects whether tokens were replaced by a generator model. This makes training more sample-efficient and faster.

**Scenario 5 (efficient NLP, constrained environments):**  
**ALBERT** – It reduces model size using parameter sharing and factorized embeddings, making it more memory-efficient while maintaining good performance.

---

### Model Comparison Table

| Model | Training differences | Size/Efficiency | Innovations | Ideal use cases |
|---|---|---|---|---|
| **RoBERTa** | Removes NSP, trains longer with larger datasets and dynamic masking | Larger than BERT but more optimized training | Improved training strategy | High-accuracy NLP tasks, document classification, QA |
| **ALBERT** | Uses parameter sharing across layers and factorized embeddings | Much smaller model with fewer parameters | Parameter sharing, memory efficiency | Large-scale NLP with limited memory resources |
| **DistilBERT** | Uses knowledge distillation from BERT | ~40% smaller and faster than BERT | Model compression via distillation | Mobile apps, real-time inference |
| **ELECTRA** | Replaces MLM with replaced-token detection during training | Very sample-efficient training | Generator–discriminator training approach | Efficient pretraining, limited compute |
| **XLM-R** | Trained on massive multilingual datasets using MLM | Large model but highly powerful | Cross-lingual representation learning | Multilingual tasks, translation, cross-lingual NLP |

## 🌟 Exercise 6: Softmax Temperature: The Randomness Regulator

### 1) Temperature Scenarios

**T = 0.2:**  
Very low temperature makes the model **more deterministic**. The model strongly prefers the highest-probability tokens, producing predictable and highly consistent outputs. However, creativity decreases and the responses may become repetitive.

**T = 1.0:**  
This is the **default balance** between randomness and predictability. The model still prefers high-probability tokens but allows some diversity in the output, producing natural and coherent text.

**T = 1.5:**  
A high temperature increases **randomness and diversity** in token selection. The model explores lower-probability words, which can produce more creative outputs but also increases the risk of incoherent or incorrect text.

---

### 2) Application Design

**Bedtime stories (creativity vs coherence):**  
A **medium to slightly high temperature (around 0.9–1.2)** is appropriate. This allows the model to generate imaginative and varied stories while still maintaining enough coherence for the story to make sense.

**Financial report summaries (accuracy/reliability):**  
A **low temperature (around 0.2–0.4)** should be used. This encourages the model to choose the most probable tokens and produce stable, consistent, and reliable summaries with minimal randomness.

---

### 3) Temperature & Bias

Temperature can influence how often **biased or sensitive associations** appear in generated text.  
At **high temperatures**, the model explores lower-probability tokens, which can sometimes surface undesirable or biased patterns present in the training data.  
At **low temperatures**, the model sticks to the most probable outputs, which may reduce random biased outputs but could still reproduce common biases if they are strongly represented in the data.

**Example:**  
If a prompt asks about occupations and genders, a high temperature might generate a wider range of associations, including stereotypes found in training data. A lower temperature might produce more consistent answers but could still reflect common societal biases unless the model has been properly mitigated.

### (Optional) Quick Generation Demo Across Temperatures
Note: Requires `transformers` and model download; skip if offline.
"""

!pip install transformers torch -q

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import torch

# Choose a causal language model
model_name = "gpt2"

# Prompt for generation
prompt = "In the future, artificial intelligence will"

pipe = pipeline(
    "text-generation",
    model=AutoModelForCausalLM.from_pretrained(model_name),
    tokenizer=AutoTokenizer.from_pretrained(model_name),
    device=0 if torch.cuda.is_available() else -1,
)

# Generate text with different temperatures
for T in [0.2, 1.0, 1.5]:
    out = pipe(prompt, max_new_tokens=40, temperature=T, do_sample=True)
    print("\n==============================")
    print("Temperature:", T)
    print("==============================")
    print(out[0]["generated_text"])

"""### Observation
Low temperature produces deterministic and safe outputs.
Higher temperature increases creativity but may reduce coherence.
This demonstrates how temperature controls randomness in language generation.
"""

